language: node_js

node_js:
  - "10"

before_script:
  - npm install -g eslint istanbul@next
  - npm install
  - npm install coveralls

script: npm run test:coveralls

branches:
  except:
    - gh-pages
